# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data\file_load.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(851, 146)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(200, 30, 301, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_ok = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ok.setGeometry(QtCore.QRect(240, 80, 151, 23))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_add_path = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_path.setGeometry(QtCore.QRect(510, 30, 75, 23))
        self.pushButton_add_path.setObjectName("pushButton_add_path")
        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close.setGeometry(QtCore.QRect(410, 80, 201, 23))
        self.pushButton_close.setObjectName("pushButton_close")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(600, 10, 221, 51))
        self.groupBox.setObjectName("groupBox")
        self.firstButton = QtWidgets.QRadioButton(self.groupBox)
        self.firstButton.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.firstButton.setChecked(True)
        self.firstButton.setObjectName("firstButton")
        self.secondButton = QtWidgets.QRadioButton(self.groupBox)
        self.secondButton.setGeometry(QtCore.QRect(120, 20, 121, 16))
        self.secondButton.setObjectName("secondButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 10, 111, 16))
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 30, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 111, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton_ok_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ok_close.setGeometry(QtCore.QRect(80, 80, 151, 23))
        self.pushButton_ok_close.setObjectName("pushButton_ok_close")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_ok.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_add_path.setText(_translate("MainWindow", "обзор"))
        self.pushButton_close.setText(_translate("MainWindow", "отмена"))
        self.groupBox.setTitle(_translate("MainWindow", "тип файла"))
        self.firstButton.setText(_translate("MainWindow", "статика"))
        self.secondButton.setText(_translate("MainWindow", "динамика"))
        self.label.setText(_translate("MainWindow", "путь к файлу"))
        self.label_2.setText(_translate("MainWindow", "имя пациента"))
        self.pushButton_ok_close.setText(_translate("MainWindow", "Добавить и закрыть"))
